"""


04b_llm_summarize.py
─────────────────────────────────────────────────────────────────────────────
Step 4b — Abstractive book-level summarisation via the local vLLM service.

Optional companion to 04_summarize.py. Where 04 produces *extractive* (TF-IDF)
summaries, this stage produces *abstractive* whole-book summaries in the same
three styles, generated by the local LLM summariser:

     • Descriptive   — what the book is about (scope, key concepts)
     • Argumentative — central thesis + supporting evidence
     • Critical       — strengths, limitations, contribution

Method: map-reduce against the OpenAI-compatible endpoint served by the local
vLLM service (adapted from csv/summarize.py). Long books are chunked ->
summarised per chunk (map) -> the partials recursively condensed until they fit
one pass. To avoid mapping every chunk three times, the book is condensed ONCE
with a neutral, fidelity-preserving map prompt (kept: key concepts, central
claims + evidence, and stated strengths/limitations), then each of the three
styles is a single cheap reduce pass over that condensed material.

NOT part of run_all.sh by default (opt-in `--llm-summaries`, off by default):
the vLLM server must be running and summarising 566 books on one GPU is slow.
The run is resumable — progress is checkpointed to the output file after every
book, and completed book ids are skipped on re-run (override with --force). If
the server goes down mid-run, a circuit-breaker aborts after N consecutive book
failures (--max-failures, default 3) instead of grinding through the rest of the
pending list; a re-run resumes from the checkpoint.

Multi-GPU: pass --endpoints host:port,host:port to fan out one worker per endpoint
(e.g. two vLLM instances on two GPUs). Books are pulled from a shared queue
(self-balancing across uneven book sizes), with a single lock-guarded checkpoint
file. An unreachable endpoint is dropped at startup; an endpoint that dies mid-run
retires after --max-failures consecutive failures and its books stay pending
(resumable) while the others carry on. Default is a single endpoint (unchanged).

Provisional: these summaries are automated abstractive output and should be
treated as provisional per the project's standing methodological principle;
verify individual claims against source text before relying on them.

Input:  json/books_clean.json, json/nlp_results.json (for the canonical book_ids)
Output: json/llm_summaries.json

Usage:
  python3 src/04b_llm_summarize.py
  python3 src/04b_llm_summarize.py --limit 5            # smoke-test first 5 books
  python3 src/04b_llm_summarize.py --only 207,2046      # specific book ids
  python3 src/04b_llm_summarize.py --force              # re-summarise everything
  python3 src/04b_llm_summarize.py --port 8004 --model summarizer --words 220
  python3 src/04b_llm_summarize.py --endpoints 127.0.0.1:8004,127.0.0.1:8005  # 2 GPUs
"""

# ── Directory layout ─────────────────────────────────────────────────────────
import pathlib as _pl
JSON_DIR = _pl.Path('json')   # all JSON/JSONL files
JSON_DIR.mkdir(exist_ok=True)

import argparse
import json
import os
import queue
import sys
import threading

sys.path.insert(0, str(_pl.Path(__file__).resolve().parent))  # sibling imports from src/
from llm_summarize_lib import approx_tokens, chunk_text, chat, resolve_api_key

try:
    from openai import OpenAI
except ImportError:
    sys.exit("Missing dep: pip install openai  (in your client env)")


# ── Config ────────────────────────────────────────────────────────────────────
MAP_WORDS = 180   # per-chunk neutral map target (short, so partials recombine)

NEUTRAL_MAP_ROLE = (
    "You are extracting faithful raw material from part of ONE book, for later "
    "synthesis. Preserve, specifically: (a) what this part is about and its key "
    "concepts; (b) the central claims or arguments and the evidence given for "
    "them; (c) any stated strengths, limitations, or evaluative judgements. Keep "
    "names, numbers, dates, and conclusions. Do not add commentary of your own."
)

STYLE_ROLES = {
    'descriptive': (
        "You write a descriptive summary of a whole book: what it is about — its "
        "scope, subject matter, and the key concepts it covers."
    ),
    'argumentative': (
        "You write an analytical summary of a book's central thesis and the main "
        "evidence or reasoning it offers in support."
    ),
    'critical': (
        "You write a critical summary of a book: its strengths, limitations, and "
        "scholarly contribution."
    ),
}
STYLES = list(STYLE_ROLES)


# ── Book-level map-reduce (approx_tokens / chunk_text / chat: llm_summarize_lib) ─
def condense_to_fit(client, model, text, map_tokens):
    """Neutrally map-reduce raw book text down to a single pass that fits
    map_tokens. Returns (condensed_text, n_raw_chunks). A book that already
    fits is returned verbatim (best fidelity — no lossy pre-summary)."""
    chunks = chunk_text(text, map_tokens)
    n_raw = len(chunks)
    if n_raw == 1:
        return text, 1
    round_no = 0
    while len(chunks) > 1:
        round_no += 1
        partials = []
        for i, ch in enumerate(chunks, 1):
            print(f"    map r{round_no} {i}/{len(chunks)}", file=sys.stderr)
            prompt = (f"Summarise this section faithfully in about {MAP_WORDS} "
                      f"words.\n\n---\n{ch}\n---")
            partials.append(chat(client, model, NEUTRAL_MAP_ROLE, prompt,
                                 max_tokens=min(2048, MAP_WORDS * 3)))
        chunks = chunk_text("\n\n".join(partials), map_tokens)
    return chunks[0], n_raw


def styled_summary(client, model, condensed, style, words):
    """One styled reduce pass over the (already-condensed) book material."""
    role = STYLE_ROLES[style]
    prompt = (f"Write flowing prose, about {words} words. Base it only on the "
              f"material below; do not invent facts.\n\n---\n{condensed}\n---")
    return chat(client, model, role, prompt, max_tokens=min(4096, words * 3))


def summarize_book(client, args, book, bid, label):
    """Condense one book, then produce the three styled summaries. Raises on LLM
    failure (the caller decides retry / skip). Returns the record dict."""
    title = book.get('title', '')
    text = book['clean_text'].strip()
    print(f"[{label}] {bid} · {title[:45]:45s} (~{approx_tokens(text)} tok)",
          file=sys.stderr)
    condensed, n_chunks = condense_to_fit(client, args.model, text, args.map_tokens)
    record = {
        'title':  title,
        'author': book.get('author', ''),
        'method': 'llm-map-reduce',
        'model':  args.model,
        'n_chunks': n_chunks,
        'approx_tokens': approx_tokens(text),
    }
    for style in STYLES:
        print(f"[{label}]   reduce: {style}", file=sys.stderr)
        record[style] = styled_summary(client, args.model, condensed, style, args.words)
    return record


# ── Endpoints ─────────────────────────────────────────────────────────────────
def parse_endpoints(args):
    """Return a list of (host, port). --endpoints (comma-separated host:port)
    overrides the single --host/--port default."""
    raw = args.endpoints or f"{args.host}:{args.port}"
    eps = []
    for item in raw.split(','):
        item = item.strip()
        if not item:
            continue
        host, _, port = item.rpartition(':')
        if not host or not port.isdigit():
            sys.exit(f"Bad --endpoints entry '{item}' (expected host:port).")
        eps.append((host, int(port)))
    if not eps:
        sys.exit("No endpoints resolved from --endpoints / --host / --port.")
    return eps


# ── Checkpointing ─────────────────────────────────────────────────────────────
def load_existing(out_path):
    if out_path.exists():
        try:
            with open(out_path, encoding='utf-8') as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            print(f"  (could not read existing {out_path}; starting fresh)",
                  file=sys.stderr)
    return {}


def save_atomic(out_path, data):
    tmp = out_path.with_suffix(out_path.suffix + '.tmp')
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    os.replace(tmp, out_path)


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(
        description="Abstractive book-level summariser (local vLLM).")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=int(os.environ.get("PORT", 8004)))
    ap.add_argument("--endpoints", default="",
                    help="comma-separated host:port list to fan out across — one "
                         "worker per endpoint, e.g. "
                         "127.0.0.1:8004,127.0.0.1:8005 for two GPUs. Overrides "
                         "--host/--port; default is a single endpoint.")
    ap.add_argument("--api-key", default=None,
                    help="vLLM API key; falls back to $API_KEY then 'EMPTY'")
    ap.add_argument("--model", default="summarizer", help="served-model-name")
    ap.add_argument("--words", type=int, default=220,
                    help="target length of each styled summary")
    ap.add_argument("--map-tokens", type=int, default=6000,
                    help="chunk size; keep well under the served --max-model-len")
    ap.add_argument("--only", default="",
                    help="comma-separated book ids to summarise (default: all)")
    ap.add_argument("--limit", type=int, default=0,
                    help="only the first N pending books (0 = no limit)")
    ap.add_argument("--force", action="store_true",
                    help="re-summarise books already present in the output")
    ap.add_argument("--max-failures", type=int, default=3,
                    help="circuit-breaker: abort after this many consecutive book "
                         "failures (a server that went down mid-run); 0 disables. "
                         "Progress is checkpointed, so a re-run resumes.")
    ap.add_argument("-o", "--out", type=_pl.Path,
                    default=JSON_DIR / 'llm_summaries.json')
    args = ap.parse_args()

    with open(str(JSON_DIR / 'books_clean.json'), encoding='utf-8') as f:
        books = json.load(f)
    with open(str(JSON_DIR / 'nlp_results.json'), encoding='utf-8') as f:
        book_ids = json.load(f)['book_ids']

    # Restrict / order the work list.
    if args.only:
        wanted = [b.strip() for b in args.only.split(',') if b.strip()]
        book_ids = [b for b in wanted if b in set(book_ids)]

    out = {} if args.force else load_existing(args.out)
    pending = [b for b in book_ids if b not in out]
    if args.limit:
        pending = pending[:args.limit]

    print(f"{len(out)} already done · {len(pending)} to summarise "
          f"({len(book_ids)} in scope)", file=sys.stderr)
    if not pending:
        print("Nothing to do.", file=sys.stderr)
        return

    # ── Build a client per endpoint; probe and keep the reachable ones ────────
    # Fail fast + friendly rather than a stack trace mid-corpus. With several
    # endpoints, an unreachable one is dropped and the run continues on the rest.
    api_key = resolve_api_key(args.api_key)
    reachable = []
    for host, port in parse_endpoints(args):
        label = f"{host}:{port}"
        client = OpenAI(base_url=f"http://{host}:{port}/v1", api_key=api_key)
        try:
            client.models.list()
            reachable.append((label, client))
        except Exception as e:  # noqa: BLE001
            print(f"⚠ endpoint {label} unreachable ({e}) — skipping",
                  file=sys.stderr)
    if not reachable:
        sys.exit("No vLLM endpoint reachable. Start the summariser server(s), then "
                 "re-run — completed books are skipped, so it resumes where it left off.")
    print(f"Fanning out across {len(reachable)} endpoint(s): "
          f"{', '.join(l for l, _ in reachable)}", file=sys.stderr)

    # ── Work queue + single locked writer; one worker thread per endpoint ─────
    # Books are pulled dynamically (not statically sharded), so a fast endpoint
    # keeps grabbing work while a slow one is mid-book — self-balancing across
    # uneven book sizes. The threads are I/O-bound on the HTTP call (GIL released),
    # so threading gives real parallelism here.
    work = queue.Queue()
    for bid in pending:
        work.put(bid)
    out_lock = threading.Lock()
    retired = []   # endpoints that gave up (their server/GPU looks down)

    def worker(label, client):
        consec = 0   # consecutive failures on THIS endpoint (per-endpoint breaker)
        while True:
            try:
                bid = work.get_nowait()
            except queue.Empty:
                return
            book = books.get(bid)
            if not book or not (book.get('clean_text') or '').strip():
                print(f"⚠ [{bid}] no clean_text — skipped", file=sys.stderr)
                continue
            try:
                record = summarize_book(client, args, book, bid, label)
            except Exception as e:  # noqa: BLE001 — one bad book must not lose progress
                consec += 1
                print(f"⚠ [{label}] [{bid}] failed ({e}) — left pending "
                      f"({consec} in a row)", file=sys.stderr)
                if args.max_failures and consec >= args.max_failures:
                    print(f"⚠ endpoint {label} retiring — it looks down "
                          f"({consec} consecutive failures); its books stay "
                          f"pending (resumable)", file=sys.stderr)
                    with out_lock:
                        retired.append(label)
                    return
                continue
            consec = 0
            with out_lock:
                out[bid] = record
                save_atomic(args.out, out)   # checkpoint after every book
                done = len(out)
            print(f"✓ [{label}] [{bid}] {record['title'][:50]:50s} "
                  f"({record['n_chunks']} chunk(s)) [{done} done]")

    threads = [threading.Thread(target=worker, args=(l, c), name=l)
               for l, c in reachable]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    remaining = work.qsize()
    if retired and remaining:
        sys.exit(f"\n⚠ {len(retired)} endpoint(s) went down ({', '.join(retired)}); "
                 f"{len(out)} book(s) saved to {args.out}, {remaining} still pending "
                 f"— re-run to finish.")
    print(f"\nDone. {len(out)} book summaries in {args.out}.")


if __name__ == '__main__':
    main()
