#!/bin/bash

############################
#
# generated by Gemini on 19/03/2026, prompted by Wong Man to segment calibre database holding
# full text for Cybernetic Bookshelf
#
# Updated 2026-07-16:
#   - TOTAL_ROWS is derived dynamically from the PDF row count. The previous
#     hardcoded value (695, then 739) silently truncated the tail of books_text
#     when the table grew, causing ~143 books (including [2641–2766] cluster —
#     Ashby, Wiener, Bateson, Beer, …) to be dropped from downstream index/entity
#     outputs while LDA read a stale superset from books_clean.jsonl.
#   - WHERE format='PDF' restricts export to PDF rows only. UNIQUE(book, format)
#     guarantees one row per book, so duplicates are eliminated at source.
#   - ORDER BY book makes chunk assignment deterministic across runs.
#
############################
# Configuration
DB_NAME="full-text-search.db"
TABLE_NAME="books_text"
NUM_SEGMENTS=25
FORMAT="PDF"

# Derive TOTAL_ROWS from the DB itself so the script self-corrects as the
# Calibre corpus grows.
TOTAL_ROWS=$(sqlite3 "$DB_NAME" "SELECT COUNT(*) FROM $TABLE_NAME WHERE format='$FORMAT';")
if [ -z "$TOTAL_ROWS" ] || [ "$TOTAL_ROWS" -eq 0 ]; then
    echo "ERROR: no $FORMAT rows found in $DB_NAME" >&2
    exit 1
fi

# Calculate rows per segment
BASE_ROWS=$((TOTAL_ROWS / NUM_SEGMENTS))
EXTRA_ROWS=$((TOTAL_ROWS % NUM_SEGMENTS))

OFFSET=0

echo "Starting export of $TOTAL_ROWS $FORMAT rows into $NUM_SEGMENTS files..."

for i in $(seq 1 $NUM_SEGMENTS); do
    if [ $i -le $EXTRA_ROWS ]; then
        LIMIT=$((BASE_ROWS + 1))
    else
        LIMIT=$BASE_ROWS
    fi

    FILE_NAME="books_text_$(printf "%02d" $i).csv"

    sqlite3 -csv -header "$DB_NAME" \
        "SELECT book AS id, searchable_text FROM $TABLE_NAME \
         WHERE format='$FORMAT' \
         ORDER BY book \
         LIMIT $LIMIT OFFSET $OFFSET;" > "$FILE_NAME"

    echo "Generated $FILE_NAME ($LIMIT rows)"

    OFFSET=$((OFFSET + LIMIT))
done

echo "Done! $NUM_SEGMENTS CSV files created."
