#!/bin/bash

############################
#
# generated by Gemini on 19/03/2026, prompted by Wong Man to segment calibre database holding 
# full text for Cybernetic Bookshelf 
#
############################
# Configuration
DB_NAME="full-text-search.db"
TABLE_NAME="books_text"
TOTAL_ROWS=695
NUM_SEGMENTS=25

# Calculate rows per segment
BASE_ROWS=$((TOTAL_ROWS / NUM_SEGMENTS))  # 27
EXTRA_ROWS=$((TOTAL_ROWS % NUM_SEGMENTS)) # 20

OFFSET=0

echo "Starting export of $TOTAL_ROWS rows into $NUM_SEGMENTS files..."

for i in $(seq 1 $NUM_SEGMENTS); do
    # 20 files will get 28 rows, the rest get 27
    if [ $i -le $EXTRA_ROWS ]; then
        LIMIT=$((BASE_ROWS + 1))
    else
        LIMIT=$BASE_ROWS
    fi

    FILE_NAME="books_text_$(printf "%02d" $i).csv"
    
    # Run SQLite command to export current chunk
    sqlite3 -csv -header "$DB_NAME" "SELECT book AS id, searchable_text FROM $TABLE_NAME LIMIT $LIMIT OFFSET $OFFSET;" > "$FILE_NAME"
    
    echo "Generated $FILE_NAME ($LIMIT rows)"
    
    # Update offset for next file
    OFFSET=$((OFFSET + LIMIT))
done

echo "Done! 25 CSV files created."
